version : '3.7'

services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Thanh@123456
      ACCEPT_EULA: Y
    ports:
      - "1444:1433"
    networks:
      - demo-mynetwork

  main-api:
    container_name: main-api
    build:
      context: ./
      dockerfile: HRM.ApiBackend\Dockerfile
    ports:
      - 3333:80
    networks :
      - demo-mynetwork
    environment:
      ASPNETCORE_ENVIRONMENT : Staging
    volumes:
      - '../EmployeeManager/HRM.ApiBackend:/app/data'
    depends_on:
      - db
    
  # chat-api:
  #   container_name: chat-api
  #   build:
  #     context : ./
  #     dockerfile: ChatApi/Dockerfile
  #   ports:
  #     - 4444:80
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Staging
  #   depends_on:
  #     - db
    
  # volumes:
  #   myapp:
  #     driver : local
  #     driver_opts:
  #       type: none
  #       o : bind
  #       device : /myapp
  # angular-app:
  #   image: awesome-angular
  #   build:
  #     context: ./
  #     dockerfile: frontend/Dockerfile # Tên Dockerfile cho Angular
  #   ports:
  #     - "4200:4200" 
  #   volumes:
  #     - ./frontend:/project
  #     - /project/node_modules
   
  
networks:
  demo-mynetwork:
    driver : bridge